version: "3.6"

services:
  indexer:
    image: ghcr.io/celenium-io/celestia-indexer:${TAG:-master}
    build:
        dockerfile: build/indexer/Dockerfile
        context: .
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    logging: &celestia-dipdup-logging
      options:
        max-size: 10m
        max-file: "5"

  api:
    restart: always
    image: ghcr.io/celenium-io/celestia-indexer-api:${TAG:-master}
    build:
      context: .
      dockerfile: build/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 127.0.0.1:9876:9876
    logging: *celestia-dipdup-logging

  db:
    command:
      - -cshared_preload_libraries=timescaledb,pg_stat_statements
      - -cpg_stat_statements.track=all
    image: timescale/timescaledb:2.12.2-pg15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB:-celestia}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d celestia"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *celestia-dipdup-logging
volumes:
  db: